In [10]:
import torch

def dropout(X,drop_prob):
    X = X.float()
    assert 0<= drop_prob <=1
    keep_prob = 1-drop_prob
    if keep_prob == 0:
        return torch.zeros_like(X)
    mask = (torch.rand(X.shape) < keep_prob).float()  #应该是rand,不应该是randn！！！
    return mask * X /keep_prob

print(torch.randn(5,5))

X = torch.arange(16).view(2,8)
print(dropout(X,0))
print(dropout(X,0.5))
print(dropout(X,1))

tensor([[-1.6246,  0.3807, -1.4745, -1.4176,  0.5576],
        [ 0.2620,  1.7255, -1.4497,  1.4803,  1.0037],
        [ 1.5267, -0.0077,  1.5033,  0.2260,  1.8998],
        [-0.0943, -1.6950,  0.0094,  1.4723, -0.5528],
        [ 0.4358,  0.6700, -0.6334,  0.4667, -1.2318]])
tensor([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14., 15.]])
tensor([[ 0.,  0.,  0.,  6.,  8.,  0., 12.,  0.],
        [16., 18., 20.,  0., 24.,  0.,  0.,  0.]])
tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])


In [15]:
def test(a):
    b=2
    print(a)
test.__code__.co_varnames

('a', 'b')